# fly.toml app configuration file generated for mealtracker on 2023-11-05T19:26:41-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mealtracker"
primary_region = "gru"

[http_service]
internal_port = 80
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[build]
dockerfile = "MealTracker.API/Dockerfile"
